name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          make install
          uv pip install coverage

      - name: Run tests with coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=gabady13_python-project-52
            -Dsonar.organization=gabady13
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc,**/templates/**,**/static/**
            -Dsonar.exclusions=**/migrations/**,**/*tests*.py,**/tests/**
